### ISSUE TITLE
[bug] mood.potion does not fire correctly for top-ups

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/libram#202]
https://github.com/Loathing-Associates-Scripting-Society/libram/blob/ab426bf1c6daf8b4aae7fbc42f6a2ee74d7c0182/src/mood.ts#L200

we think we solved the issue on the discord at [1:31 am EST](https://discord.com/channels/466605739838930955/864070665615179786/929261039076380742); mood.potion fires correctly for the initial bulk cast within garbage-collector but does not fire correctly on effect top-ups. bean and phred think this is due to fractional amounts being passed into the buy (at the line i linked above); might just be a ceil or something? i do not know if i am comfortable making this change but i am a Good Documentation Friend who wanted to document the bug.

have a nice day folks love yall

**Comment by horrible-little-slime** [comment]
I think there's a solution here but it's not quite as trivial as it seems. We have a maxPricePerTurn, so we need to re-calculate the price per turn based on the limit (or just change our existing calculation), and make sure to ceil/floor values as necessary. Alternately, we can invent a time machine and give js ints.

**Comment by horrible-little-slime** [comment]
(hopefully) resolved as of 0.5.7

**Comment by horrible-little-slime** [comment]
Going to unilaterally declare this resolved as of 0.5.7 because no one has complained since then.
