### ISSUE TITLE
Proposal: Don't use type guessing heuristic for get()

### ISSUE THREAD

**Issue by pastelmind** [Loathing-Associates-Scripting-Society/libram#31]
## Problem Statement

Currently, there is a discrepancy between the type declaration and implementation of [`get()`](https://github.com/Loathing-Associates-Scripting-Society/libram/blob/07ff234759d06ca009e28eec82ff65aad123854f/src/property.ts#L88-L128):

* The implementation guesses the type of a KoLmafia property using its name.
* The typing for built-in properties is controlled by union types in [`propertyTypings.ts`](https://github.com/Loathing-Associates-Scripting-Society/libram/blob/07ff234759d06ca009e28eec82ff65aad123854f/src/propertyTyping.ts). Notably, this also applies to custom KoLmafia properties.

For example, `get()` converts any property name ending with "Monster" to a `Monster` object (see [`isMonsterProperty()`](https://github.com/Loathing-Associates-Scripting-Society/libram/blob/07ff234759d06ca009e28eec82ff65aad123854f/src/propertyTyping.ts#L27-L30)). However, the TypeScript compiler looks up the property name from the [`MonsterProperty`](https://github.com/Loathing-Associates-Scripting-Society/libram/blob/07ff234759d06ca009e28eec82ff65aad123854f/src/propertyTyping.ts#L26) union type.

This can cause problems in two scenarios:

1. KoLmafia may gain a property whose name ends with "Monster", but which should not be converted to a monster. (ex: `hasEncounteredSomeMonster`)
2. The user may define a custom property whose name ends with "Monster".

In either case, the new property would be unusable with `get()`:

```ts
// At compile time, TypeScript assumes that the type of a is `unknown`
// At run time, `get()` converts the property to a Monster
// In reality, the property should be coerced to a boolean
let a = get("hasEncounteredSomeMonster");
```

This is a contrived example, but there may be more cases that would force us to use more and more complicated guesses down the road.

## Proposal
Let's abandon the type guessing mechanism altogether. Instead, use a lookup table/switch...case statement/etc. that maps built-in property names to their intended types.

This satisfies the following goals:

1. For known (built-in) KoLmafia properties, compile-time assumption matches run-time behavior
2. For new or custom KoLmafia properties, we make no assumptions about how to coerce the type

The lookup table code could be generated by `tools/parseDefaultProperties.ts`.

## Alternatives

1. Prohibit the use of `get()` for custom KoLmafia properties (i.e. only allow known property names).
    - This might be too extreme

**Comment by gausie** [comment]
My preference would be to type any unknown property as `unknown`
