### ISSUE TITLE
Implement since

### ISSUE THREAD

**Issue by pastelmind** [Loathing-Associates-Scripting-Society/libram#7]
ASH has a neat [`since`](https://wiki.kolmafia.us/index.php/Since) statement that checks KoLmafia's version. Unfortunately it's a custom statement, not a built-in function, so the JS runtime doesn't have it.

I made a utility library, [kolmafia-util](https://github.com/pastelmind/kolmafia-util), that replicates this feature in JS. It would be nice to integrate it into libram.

## Proposal

Add two functions:
```ts
function sinceKolmafiaVersion(majorVersion: number, minorVersion: number): void;
function sinceKolmafiaRevision(revision: number): void;
```

These would throw a `KolmafiaVersionError` if the current version/revision is less than the required amount.

## How about implementing it in KoLmafia's JS Runtime?

* Extending the JS syntax with a `since` statement will break TS/JS tools
* Adding an ASH/JS library function in KoLmafia would be easy, but it would be redundant with the existing `since` statement.

**Comment by gausie** [comment]
It's possible this should be implemented by mafia (i.e. exposed to JS natively). @phulin what do you think?

**Comment by pastelmind** [comment]
If we're talking about adding a `since` statement, I disagree. TS/JS tooling won't support it.

If we're talking about implementing it as an ASH/JS function...we already have a since statement in ASH, and it would be redundant.

Also, it's trivial to implement it in JS.

**Comment by gausie** [comment]
> If we're talking about adding a `since` statement, I disagree. TS/JS tooling won't support it.
Yeah this would be bad
> If we're talking about exposing a library function in KoLmafia...we already have a since statement in ASH, and it would be redundant.
sort of
> Also, it's trivial to implement it in JS.
ok lets do it
